package com.myRoomie.constants;

public enum ResponseCode {
	
	OK                     (HTTPCode.OK, "Success"), 
	
	NOT_FOUND              (HTTPCode.NO_CONTENT, "Not found"), 
	NO_SALESMAN_FOUND      (HTTPCode.NO_CONTENT, "No salesman found"), 
	NO_USER_FOUND          (HTTPCode.NO_CONTENT, "No user found"), 
	NO_CITY_FOUND          (HTTPCode.NO_CONTENT, "No city found"), 
	NO_AREA_FOUND          (HTTPCode.NO_CONTENT, "No area found"), 
	NO_PLAN_FOUND          (HTTPCode.NO_CONTENT, "No plan found"), 
	NO_CUSTOMER_FOUND      (HTTPCode.NO_CONTENT, "No customer found"), 
	NO_CUSTOMER_DOC_FOUND  (HTTPCode.NO_CONTENT, "No customer document found"), 
	NO_COMPANY_FOUND       (HTTPCode.NO_CONTENT, "No company found"), 
	NO_PRODUCT_FOUND       (HTTPCode.NO_CONTENT, "No product found"), 
	NO_INVENTORY_FOUND     (HTTPCode.NO_CONTENT, "No inventory found"), 
	NO_SERVICE_FOUND       (HTTPCode.NO_CONTENT, "No service found"), 
	NO_DEPARTMENT_FOUND    (HTTPCode.NO_CONTENT, "No department found"), 
	NO_ROLE_FOUND          (HTTPCode.NO_CONTENT, "No role found"), 
	NO_CATEGORY_FOUND      (HTTPCode.NO_CONTENT, "No category found"), 
	NO_VENDOR_FOUND        (HTTPCode.NO_CONTENT, "No vendor found"), 
	NO_GLOBAL_DATA_FOUND   (HTTPCode.NO_CONTENT, "No global data is present"),
	NO_TASK_FOUND          (HTTPCode.NO_CONTENT, "No task is found"),
	NO_NOTIFICATION_TOKEN_FOUND(HTTPCode.NO_CONTENT, "No notification token found"),
	NO_ADMIN_FOUND         (HTTPCode.NO_CONTENT, "No admin found"),
	NO_LEAD_FOUND         (HTTPCode.NO_CONTENT, "No lead found"),
	NO_LEAVE_FOUND         (HTTPCode.NO_CONTENT, "No leave found"),
	NO_DETAIL_FOUND        (HTTPCode.NO_CONTENT, "No detail found"),
	NO_USER_ATTENDANCE_FOUND(HTTPCode.NO_CONTENT,"No user attendance data is found"),
	NO_PARTNER_FOUND       (HTTPCode.NO_CONTENT, "No partner found"),
	NO_PROPERTY_FOUND    (HTTPCode.NO_CONTENT, "No Property found."),
    PROPERTY_PRESENT_NAME_LOCATION(HTTPCode.NO_CONTENT, "Property already present with name and location!"),
	NEAR_BY_PLACES_NOT_PRESENT    (HTTPCode.NO_CONTENT, "NearByPlaces are not present"),
	ADDRESS_NOT_PRESENT    (HTTPCode.NO_CONTENT, "Address is not present"),
	
	BAD_REQUEST            (HTTPCode.BAD_REQUEST, "Request made is not correct"),
	INCORRECT_JSON_DATA    (HTTPCode.BAD_REQUEST, "Json is not in correct format"),
	NO_DATA_PRESENT        (HTTPCode.BAD_REQUEST, "No data is present"), 
	NAME_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Name is not present"), 
	ID_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Id is not present"), 
	VALIDITY_NOT_PRESENT   (HTTPCode.BAD_REQUEST, "Validity is not present"), 
	MOBILE_NUM_NOT_PRESENT (HTTPCode.BAD_REQUEST, "Mobile Number not present"), 
	PASSWORD_NOT_PRESENT   (HTTPCode.BAD_REQUEST, "Password is not present"),
	EMAIL_NOT_PRESENT      (HTTPCode.BAD_REQUEST, "Email is not present"),
	FILE_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "File is not present"),
	NO_PRODUCT_PRESENT     (HTTPCode.BAD_REQUEST, "Products are not present"),
	FLAT_NUM_NOT_PRESENT   (HTTPCode.BAD_REQUEST, "Flat number is not present"),
	LOCALITY_NOT_PRESENT   (HTTPCode.BAD_REQUEST, "Locality is not present"),
	CITY_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "City is not present"),
	PROPERTY_GENDER_TYPE   (HTTPCode.BAD_REQUEST, "propertyGenderType is not present"),
	PROPERTY_TYPE   	   (HTTPCode.BAD_REQUEST, "propertyType is not present"),
	STATE_NOT_PRESENT      (HTTPCode.BAD_REQUEST, "State is not present"),
	COUNTRY_NOT_PRESENT    (HTTPCode.BAD_REQUEST, "Country is not present"),
	PINCODE_NOT_PRESENT    (HTTPCode.BAD_REQUEST, "Pincode is not present"),
	DESIGNATION_NOT_PRESENT(HTTPCode.BAD_REQUEST, "Designation is not present"),
	PROFILE_PIC_NOT_PRESENT(HTTPCode.BAD_REQUEST, "Profile pic is not present"),
	METHOD_ARGUMENT_INVALID(HTTPCode.BAD_REQUEST, "method argument is not valid"),
	PLAN_IDS_NOT_PRESENT   (HTTPCode.BAD_REQUEST, "Plan ids not present"),
	GST_NOT_PRESENT        (HTTPCode.BAD_REQUEST, "GST number is not present"),
	NOTIFICATION_TOKEN_NOT_PRESENT(HTTPCode.BAD_REQUEST, "Notification token is not present"),
	PLATFORM_NOT_PRESENT   (HTTPCode.BAD_REQUEST, "Platform is not present"),
	DEVICE_ID_NOT_PRESENT  (HTTPCode.BAD_REQUEST, "Device id is not present"),
	DATE_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Date is not present"),
	NO_DETAIL_PRESENT      (HTTPCode.BAD_REQUEST, "Detail is not present"),
	MARKED_FROM_NOT_PRESENT(HTTPCode.BAD_REQUEST,"Marked from is not present"), 
	CUSTOMER_NOT_PRESENT   (HTTPCode.BAD_REQUEST,"Customer is not present"), 
	UDID_NOT_PRESENT       (HTTPCode.BAD_REQUEST,"Udid is not present"), 
	NO_CHECKOUTLIST_PRESENT(HTTPCode.BAD_REQUEST,"Checkout list is not present"), 
	ONLY_ONE_PARAM_IS_REQUIRED(HTTPCode.BAD_REQUEST,"Please send only one parameter"),
	SERVICE_ID_NOT_PRESENT (HTTPCode.BAD_REQUEST, "Service id is not present"),

	INVALID_TOKEN          (HTTPCode.UNAUTHORIZED, "Token is not valid"),
	TOKEN_NOT_PRESENT      (HTTPCode.UNAUTHORIZED, "Token is not present"),
	
	NOT_ALLOWED            (HTTPCode.FORBIDDEN, "You are not allowed to perform this request"),
	CURRENT_DEVICE_LOGIN_NOT_ALLOWED(HTTPCode.FORBIDDEN, "You are not allowed to login from this device"),
	OLD_DEVICE_LOGIN_NOT_ALLOWED    (HTTPCode.FORBIDDEN, "Please upgrade to new version"),
	
	METHOD_NOT_ALLOWED     (HTTPCode.METHOD_NOT_ALLOWED, "This method is not allowed on this request"),
	OPERATION_NOT_ALLOWED  (HTTPCode.METHOD_NOT_ALLOWED, "This operation is not allowed"),

	USER_ADHAAR_DETAILS_ALREADY_EXISTS(HTTPCode.CONFLICT, "User adhaar details already exist"),
	PHONE_ALREADY_EXISTS              (HTTPCode.CONFLICT, "Phone number already exist"),
	RECEIPT_NUM_ALREADY_PRESENT       (HTTPCode.CONFLICT, "Receipt number already exist"),
	
	FILE_TYPE_NOT_SUPPORTED(HTTPCode.UNSUPPORTED, "This file type is not supported"),
	REQUEST_NOT_SUPPORTED  (HTTPCode.UNSUPPORTED, "This request is not supported"),
	
	INVALID_ID             (HTTPCode.INVALID, "Invalid id"),
	INVALID_CITY_ID        (HTTPCode.INVALID, "City id is not valid"),
	INVALID_AREA_ID        (HTTPCode.INVALID, "Area id is not valid"),
	INVALID_PLAN_ID        (HTTPCode.INVALID, "Plan id is not valid"),
	INVALID_SALESMAN_ID    (HTTPCode.INVALID, "Salesman id is not valid"),
	INVALID_CUSTOMER_ID    (HTTPCode.INVALID, "Customer id is not valid"),
	INVALID_CUSTOMER_DOC_ID(HTTPCode.INVALID, "Customer document id is not valid"),
	INVALID_EKYC_STATUS    (HTTPCode.INVALID, "Ekyc status type is not valid"),
	INVALID_PAYMENT_STAUTS    (HTTPCode.INVALID, "Payment status type  is not valid"),
	INVALID_AMOUNT         (HTTPCode.INVALID, "Amount is not valid"),
	INVALID_LOGIN_DETAILS  (HTTPCode.INVALID, "Login details are not valid"),
	INVALID_LOGIN  (HTTPCode.INVALID, "User with this mobile number is not registered! Please contact Admin"),
	INVALID_DOCUMENT_TYPE  (HTTPCode.INVALID, "Document type is not valid"),
	INVALID_USER_ID        (HTTPCode.INVALID, "User Id is not valid"),
	INVALID_ROLE_TYPE      (HTTPCode.INVALID, "Role type is not valid"),
	INVALID_COMPANY_ID     (HTTPCode.INVALID, "Company id is not valid"),
	INVALID_PARENT_COMPANY_ID(HTTPCode.INVALID, "Parent company id is not valid"),
	INVALID_PRODUCT_ID     (HTTPCode.INVALID, "Product id is not valid"),
	INVALID_INVENTORY_ID   (HTTPCode.INVALID, "Inventory id is not valid"),
	INVALID_STATUS_CODE    (HTTPCode.INVALID, "Status code is not valid"),
	INVALID_INVENTORY_TYPE (HTTPCode.INVALID, "Inventory type is not valid"),
	INVALID_LATITUDE       (HTTPCode.INVALID, "Latitude is not valid"),
	INVALID_LONGITUDE      (HTTPCode.INVALID, "Longitude is not valid"),
	INVALID_SERVICE_ID     (HTTPCode.INVALID, "Service id not valid"),
	INVALID_ADDRESS        (HTTPCode.INVALID, "Address is not valid"),
	INVALID_DEPARMENT_ID   (HTTPCode.INVALID, "Department id is not valid"),
	INVALID_ROLE_ID        (HTTPCode.INVALID, "Role id is not valid"),
	INVALID_CATEGORY_ID    (HTTPCode.INVALID, "Category id is not valid"),
	INVALID_VENDOR_ID      (HTTPCode.INVALID, "Vendor id is not valid"),
	INVALID_ASSIGNER_ID    (HTTPCode.INVALID, "Assigner id is not valid"),
	INVALID_RECIEVER_ID    (HTTPCode.INVALID, "Reciever id is not valid"),
	USER_NOT_MAPPED_TO_AREA(HTTPCode.INVALID, "User is not allowed in this area"),
	INVALID_FILE_TYPE      (HTTPCode.INVALID, "File type is not valid"),
	INVALID_DATE           (HTTPCode.INVALID, "Date is not valid"),
	INVALID_FROM_DATE      (HTTPCode.INVALID, "From date is not valid"),
	INVALID_TILL_DATE      (HTTPCode.INVALID, "Till date is not valid"),
	INVALID_PAGE           (HTTPCode.INVALID, "Page is not valid"),
	INVALID_ADMIN_ID       (HTTPCode.INVALID, "Admin id is not valid"),
	INVALID_PUNCH_ID       (HTTPCode.INVALID, "Punching id is not valid"),
	INVALID_PUNCHING_TYPE  (HTTPCode.INVALID, "Punching type is not valid"),
	INVALID_PUNCHING_TIME  (HTTPCode.INVALID, "Punching time is not valid"),
	INVALID_LEAVE_ID       (HTTPCode.INVALID, "Leave id is not valid"),
	INVALID_PURPOSE        (HTTPCode.INVALID, "Purpose is not valid"),
	INVALID_CAF_ID         (HTTPCode.INVALID, "CAF id is not valid"),
	INVALID_STANDARD_PACKING_QUANTITY(HTTPCode.INVALID, "Standard packing quantity is not valid"),
	INVALID_UNIT           (HTTPCode.INVALID, "Unit is not valid"),
	INVALID_SEARCH_FIELD   (HTTPCode.INVALID, "Search field is not valid"),
	INVALID_SUB_DETAIL_ID  (HTTPCode.INVALID, "Sub detail id is not valid"),
	INVALID_CONSUMED_QTY   (HTTPCode.INVALID, "Consumed quantity is not valid"),
	INVALID_INVENTORY_ASSIGNMENT_ID(HTTPCode.INVALID,"Inventory assignment id is not valid"),
	INVALID_INVENTORY_ASSIGNMENT_TYPE(HTTPCode.INVALID,"Inventory assignment type is not valid"),
	INVALID_USER_ATTENDANCE_ID(HTTPCode.INVALID,"User attendance id is not valid"),
	INVALID_STATUS         (HTTPCode.INVALID, "Status is not valid"),
	INVALID_SHIFT_START_TIME(HTTPCode.INVALID, "Shift start time is not valid"),
	INVALID_SHIFT_END_TIME (HTTPCode.INVALID, "Shift end time is not valid"),
	INVALID_REPORTING_MANAGER_ID(HTTPCode.INVALID, "Reporting manager id is not valid"),
	INVALID_PARTNER_ID     (HTTPCode.INVALID, "Partner id is not valid"),
	INVALID_QUANTITY       (HTTPCode.INVALID, "Quantity is not valid"),
	INVALID_EKYC_TIMESTAMP (HTTPCode.INVALID, "EKYC timestamp is not valid"),
	INVALID_OLD_PASSWORD   (HTTPCode.INVALID, "Old Password is not valid"),
	INVALID_NEW_PASSWORD   (HTTPCode.INVALID, "New Password is not valid"),
	INVALID_TYPE_CODE      (HTTPCode.INVALID, "Type code is not valid"),
	EMPTY_REQUEST       (HTTPCode.BAD_REQUEST,"Empty Request !"), 
	
	/* user document */
	INVALID_USER_DOCUMENT_ID   (HTTPCode.INVALID, "UserDocument id is not valid"),
	DOCUMENT_TYPE_NOT_PRESENT  (HTTPCode.BAD_REQUEST,"UserDocument type is not present"),
	USER_ID_NOT_PRESENT (HTTPCode.BAD_REQUEST,"UserId  is not present"),
	NO_USER_DOCUMENT_FOUND  (HTTPCode.NO_CONTENT, "No user document found"), 
	
	/* master charge */
	INVALID_MASTER_CHARGE_ID   (HTTPCode.INVALID, "Master charge id is not valid"),
	CHARGE_NOT_PRESENT  (HTTPCode.BAD_REQUEST,"Charge is not present"),
	AMOUNT_NOT_PRESENT  (HTTPCode.BAD_REQUEST,"Amount is not present"),
	NO_MASTER_CHARGE_FOUND  (HTTPCode.NO_CONTENT, "No master charge found"), 
	/* source master */
	INVALID_SOURCE_MASTER_ID   (HTTPCode.INVALID, "Source master id is not valid"),
	SOURCE_ID_NOT_PRESENT  (HTTPCode.BAD_REQUEST,"Source Master Id is not present"),
	NO_SOURCE_MASTER_FOUND  (HTTPCode.NO_CONTENT, "No master charge found"), 
	/* followUp master */
	INVALID_FOLLOW_UP_MASTER_ID   (HTTPCode.INVALID, "FollowUpReasonMaster id is not valid"),
	FOLLOW_UP_MASTER_ID_NOT_PRESENT  (HTTPCode.BAD_REQUEST,"FollowUpReasonMaster Id is not present"),
	FOLLOW_UP_MASTER_NOT_FOUND  (HTTPCode.NO_CONTENT, "FollowUpReasonMaster not found !"), 
	
	/* customer info */
	INVALID_CUSTOMER_INFO_ID   (HTTPCode.INVALID, "CustomerInfo id is not valid"),
	
	/*task */
	INVALID_TASK_ID        (HTTPCode.INVALID, "Task id is not valid"),
	CUSTOMER_USERNAME_NOT_PRESENT    (HTTPCode.INVALID, "Customer username is not present"),
	CUSTOMER_NAME_NOT_PRESENT(HTTPCode.INVALID, "Customer name is not present"),
	CREATED_BY_EMPLOYEE_NOT_PRESENT(HTTPCode.INVALID, "Created by employee name is not present"),
	SERVICE_AREA_NOT_PRESENT(HTTPCode.INVALID, "Service area is not present"),
	INVALID_PANMENT_DATE(HTTPCode.INVALID, "Payment date  is not valid"),
	TASK_TYPE_NOT_PRESENT(HTTPCode.INVALID, "Task type is not present"),	
	PAYMENT_STATUS_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Payment status is not present"), 
	EKYC_STAUTS_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Ekyc status is not present"), 
	INTEGRATION_MISSED_CALL_ERROR                  (HTTPCode.SERVER_ERROR, "No Data found in integeration !"), 
	
	
	ERROR                  	(HTTPCode.SERVER_ERROR, "Internal Server Error"), 
	ERROR_IN_DELETING      	(HTTPCode.SERVER_ERROR, "Error In Deleting"), 
	ERROR_IN_UPLOADING     	(HTTPCode.SERVER_ERROR, "Error in uploading content"),
	ERROR_IN_DOWNLOADING   	(HTTPCode.SERVER_ERROR, "Error in downloading content"),
	ERROR_IN_PARSING       	(HTTPCode.SERVER_ERROR, "Error in parsing"),
	ERROR_IN_CREATING_JSON 	(HTTPCode.SERVER_ERROR, "Error in creating json"),
	ERROR_IN_SAVING 		(HTTPCode.SERVER_ERROR, "Error in saving."),
	ERROR_IN_UPDATING 		(HTTPCode.SERVER_ERROR, "Error in updating."),
	
	/* crm */
	USER_TYPE_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "User Type is not present"),
	USER_NAME_NOT_PRESENT                (HTTPCode.BAD_REQUEST, "Username is not present"),
	DEVICE_MAC_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Device mac is not present"),
	UAN_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Uan is not present"),
	IMEI_NOT_PRESENT                (HTTPCode.BAD_REQUEST, "IMEI is not present"), 
	PAYMENT_MODE_NOT_PRESENT                (HTTPCode.BAD_REQUEST, "Payment mode is not present"), 
	PAYMENT_DATE_NOT_PRESENT                (HTTPCode.BAD_REQUEST, "Payment date is not present"), 
	NO_PAYMENT_COLLECTION_FOUND      (HTTPCode.NO_CONTENT, "No payment collection found"),
	NO_NO_COLLECTION_FOUND      (HTTPCode.NO_CONTENT, "No collection not found"), 
	INVALID_PAYMENT_COLLECTION_ID           (HTTPCode.INVALID, "Payment collection id is not valid"),
	NO_CRM_USER_FOUND         (HTTPCode.NO_CONTENT, "Crm user not found with %s id !"),
	NO_CRM_LEASE_CIRCUIT_BILL_FOUND         (HTTPCode.NO_CONTENT, "Crm Lease Circuit Bill not found !"),
	ALREADY_REVERT_PAYMENT_COLLECTION  (HTTPCode.BAD_REQUEST,"This Payment Collection is already reverted !"),
	CRM_USER_ID_NOT_PRESENT                (HTTPCode.BAD_REQUEST, "Crm userId is not present"), 
	NO_CRM_STATS_FOUND         (HTTPCode.NO_CONTENT, "Crm Collection stats are not found !"),
	/* sub area */
	INVALID_SUB_AREA_ID   (HTTPCode.INVALID, "SubArea id is not valid"),
	AREA_ID_NOT_PRESENT (HTTPCode.BAD_REQUEST,"AreaId  is not present"),
	NO_SUB_AREA_FOUND  (HTTPCode.NO_CONTENT, "No  Sub Area found"),
	/* crmDisconnectionRequest */
	NO_CRM_DISCONNECTION_REQUEST_FOUND         (HTTPCode.NO_CONTENT, "No CrmDisconnectionRequest found"),
	TYPE_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "CrmDisconnection type is not present"),
	INVALID_CRM_DISCONNECTION_REQUEST_ID        (HTTPCode.INVALID, "CrmDisconnection Id is not valid"),
	INVALID_CRM_DISCONNECTION_REQUEST_TYPE       (HTTPCode.INVALID, "CrmDisconnection type is not valid"),
	ALREADY_ASSIGNED_CRM_DISCONNECTION_REQUEST  (HTTPCode.BAD_REQUEST,"This Crm Request is already assigned !"),
	
	/* Punch in and out */
	ALREADY_PUNCHED_IN   (HTTPCode.BAD_REQUEST, "You have already punched in"),
	ALREADY_PUNCHED_OUT   (HTTPCode.BAD_REQUEST, "You have already punched out"),
	NOT_PUNCHED_IN   (HTTPCode.BAD_REQUEST, "You did not punched in today"),
	
	/* assigned over due */
	INVALID_ASSIGENED_OVER_DUE_ID   (HTTPCode.INVALID, "AssignedOverDue id is not valid"),
	NO_ASSIGENED_OVER_DUE_FOUND   (HTTPCode.INVALID, "No AssignedOverDue found"),
	EMPLOYEE_ID_NOT_PRESENT                (HTTPCode.BAD_REQUEST, "Employee id is not present"),
	EMPLOYEE_ALREADY_EXISTS                (HTTPCode.BAD_REQUEST, "Employee is already exists"),
	EMPLOYEE_ADDED                (HTTPCode.BAD_REQUEST, "Employee is successfully added"),
	INVALID_EMPLOYEE_ID        (HTTPCode.INVALID, "Employee Id is not valid"),
	INVALID_EMPLOYEE_EMAIL        (HTTPCode.INVALID, "Employee EMAIL is not present"),
	/*emplyee tracking */
	NO_EMPLOYEE_TRACKIMG_FOUND    (HTTPCode.NO_CONTENT, "No tracking record found"), 
	NO_PAYMENT_FOUND   (HTTPCode.INVALID, "No payment record found"), 
	ALREADY_LOGIN(HTTPCode.BAD_REQUEST, "You have already login !"), 
	INVALID_EKYC_STAUTS(HTTPCode.INVALID, "Ekyc status is not valid"),
	INVALID_CUSTOMER_WORKS_STAUTS(HTTPCode.INVALID, "Customer workStatus is not valid"),
	 INVALID_CRM_MOBILE_NO(HTTPCode.INVALID, "No Usre found with this mobile Number!"),
	 WORK_STAUTS_NOT_PRESENT       (HTTPCode.BAD_REQUEST, "Work status is not present"), 
	 INVALID_PAYMENT_STATUS_      (HTTPCode.BAD_REQUEST, "PaymentStatus is Pending !"),
	 INVALID_CUSTOMER_EKYC_STATUS       (HTTPCode.BAD_REQUEST, "EkycStatus is not approved !"),
	 INVALID_APPROVED_WORKS_STATUS       (HTTPCode.BAD_REQUEST, "Customer worksStatus is not approved !"),
	 INVALID_NEW_WORKS_STATUS       (HTTPCode.BAD_REQUEST, "Customer worksStatus is not in new state !"),
	 INVALID_WIRING_WORKS_STATUS       (HTTPCode.BAD_REQUEST, "Customer worksStatus is not in Wiring state !"),
	 INVALID_EKYC_ACCOUNT_STATUS       (HTTPCode.BAD_REQUEST, "Ekyc isAccount status is false!"),
	 INVALID_INSTALLATION_WORKS_STATUS       (HTTPCode.BAD_REQUEST, "Customer worksStatus is not in Installation state !"),
	 INVALID_PENDING_WORKS_STATUS       (HTTPCode.BAD_REQUEST, "Customer worksStatus is not in Pending Confirmation state !"),
	CHARGE_ID_NOT_PRESENT			(HTTPCode.BAD_REQUEST,"Charge Id is not present"),
	LEAD_ID_NOT_PRESENT  			(HTTPCode.BAD_REQUEST,"Lead Id is not present"),
	ALREADY_ASSIGNED_ENQUIRY  		(HTTPCode.BAD_REQUEST,"This enquiry is already assigned !"),
	ALREADY_ASSIGNED_LEAD			(HTTPCode.BAD_REQUEST,"This lead is already assigned !"),
	COUPON_CODE_NAME_NOT_PRESENT  	(HTTPCode.BAD_REQUEST,"Coupon Code Name not present."),
	NO_COUPON_CODE_FOUND 		  	(HTTPCode.BAD_REQUEST,"Coupon Code does not exists."),
	COUPON_CODE_EXPIRED 		  	(HTTPCode.BAD_REQUEST,"Coupon Code is expired."),
	COUPON_CODE_ALREADY_PRESENT 	(HTTPCode.BAD_REQUEST,"Coupon Code is already present."),
	COUPON_CODE_NOT_ACTIVE 		  	(HTTPCode.BAD_REQUEST,"Coupon Code is not active.");
	
	
	
	private String code;
	private String message;
	public String getCode() {
		return code;
	}
	public String getMessage() {
		return message;
	}

    ResponseCode(String code, String message) {
		this.code = code;
		this.message = message;
	}
}
